'use client';

import { LintDashboard } from '@lintscope/ui';
import { useSearchParams } from 'next/navigation';
import { useMemo } from 'react';
import { parseConnectionParams, type StudioConnection } from '../_lib/connection';
import { useStudioData } from '../_lib/use-studio-data';
import { ConnectionError } from './connection-error';
import { ConnectionPending } from './connection-pending';

export function StudioClient() {
  const params = useSearchParams();
  const parsed = useMemo(() => parseConnectionParams(params), [params]);

  if (!parsed.ok) {
    return (
      <ConnectionError
        title="Invalid studio URL"
        message={parsed.reason}
        hint="This URL is generated by the lintscope CLI. If you hand-edited it, double-check host, port, and token."
        showCommand={parsed.missing.length === 0}
      />
    );
  }

  return <StudioBody connection={parsed.connection} />;
}

function StudioBody({ connection }: { connection: StudioConnection }) {
  const { state } = useStudioData(connection);

  if (state.kind === 'pending') {
    return <ConnectionPending />;
  }

  if (state.kind === 'auth-error') {
    return (
      <ConnectionError
        title="Token rejected by studio server"
        message="The CLI created a single-use token. Was this URL hand-edited, or is an older browser tab still open?"
        hint={`Close this tab and reopen the studio from a fresh \`${connection.host ?? 'localhost'}\` CLI run.`}
      />
    );
  }

  if (state.kind === 'connection-error') {
    return (
      <ConnectionError
        title="Couldn't reach the studio"
        message={state.message}
        hint="Your `lintscope` CLI may have exited. Restart it and reopen the studio from the URL it prints."
      />
    );
  }

  if (state.kind === 'schema-error') {
    return (
      <ConnectionError
        title="Studio server returned an unexpected shape"
        message={`Endpoint ${state.endpoint}: ${state.details}`}
        hint="Your CLI version may be newer or older than this hosted UI. Try `npm i -g lintscope@latest`."
        showCommand={false}
      />
    );
  }

  // state.kind === 'ready'
  return (
    <div className="flex flex-col gap-6">
      <header className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <p className="font-mono text-xs uppercase tracking-widest text-zinc-500">
            {state.init.name} · studio
          </p>
          <h1 className="text-2xl font-semibold tracking-tight">Lint diagnostics</h1>
          <p className="text-xs text-zinc-500 dark:text-zinc-500">
            {state.init.linters.map((l) => `${l.name}@${l.version}`).join(', ')}
            {state.init.capabilities.watch && (
              <span className="ml-2 inline-flex items-center gap-1 rounded bg-emerald-50 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-emerald-700 ring-1 ring-inset ring-emerald-600/20 dark:bg-emerald-950/40 dark:text-emerald-300 dark:ring-emerald-400/30">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
                watching
              </span>
            )}
            {!state.init.capabilities.scan && (
              <span className="ml-2 inline-flex items-center gap-1 rounded bg-zinc-100 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-zinc-600 ring-1 ring-inset ring-zinc-500/20 dark:bg-zinc-900 dark:text-zinc-400 dark:ring-zinc-400/20">
                <span className="h-1.5 w-1.5 rounded-full bg-zinc-400" />
                render-only
              </span>
            )}
          </p>
        </div>
      </header>
      <LintDashboard report={state.report} />
    </div>
  );
}
