'use client';

import { STUDIO_DISCOVERY_PORTS } from '@lintscope/api-schema';
import { LintDashboard } from '@lintscope/ui';
import { useSearchParams } from 'next/navigation';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { StudioAuthError, StudioConnectionError, studioApi } from '../_lib/api-client';
import {
  type ParsedStudioParams,
  parseConnectionParams,
  type StudioConnection,
  type StudioTarget,
} from '../_lib/connection';
import { useStudioData } from '../_lib/use-studio-data';
import { ConnectionError } from './connection-error';
import { ConnectionPending } from './connection-pending';

const DEFAULT_HOST = '127.0.0.1';

export function StudioClient() {
  const params = useSearchParams();
  const parsed = useMemo(() => parseConnectionParams(params), [params]);

  if (!parsed.ok) {
    return (
      <ConnectionError
        title="Invalid studio URL"
        message={parsed.reason}
        hint="This URL is generated by the lintscope CLI. If you hand-edited it, double-check the params."
        showCommand
      />
    );
  }

  return <StudioConnector params={parsed.params} />;
}

type ResolveState =
  | { kind: 'resolving' }
  | { kind: 'ready'; connection: StudioConnection }
  | { kind: 'error'; error: unknown };

/**
 * Resolve a full connection from the URL params:
 *  - `port` given → handshake at that host:port (token from URL or handshake);
 *  - `port` absent → probe the discovery range, handshaking each until one
 *    answers. The token is never read from the URL when absent.
 */
async function resolveConnection(params: ParsedStudioParams): Promise<StudioConnection> {
  const host = params.host ?? DEFAULT_HOST;
  const withName = (t: StudioTarget): StudioTarget =>
    params.name ? { ...t, name: params.name } : t;

  if (params.port) {
    const target = withName({ host, port: params.port });
    const token = params.token ?? (await studioApi.handshake(target)).token;
    return { ...target, token };
  }

  let lastError: unknown;
  for (const port of STUDIO_DISCOVERY_PORTS) {
    const target = withName({ host, port: String(port) });
    try {
      const hs = await studioApi.handshake(target);
      return { ...target, token: hs.token, name: hs.name };
    } catch (err) {
      lastError = err;
    }
  }
  throw new StudioConnectionError(
    `No lintscope studio found on ports ${STUDIO_DISCOVERY_PORTS[0]}–${STUDIO_DISCOVERY_PORTS.at(-1)}. Is the CLI running?`,
    lastError,
  );
}

function useResolvedConnection(params: ParsedStudioParams): ResolveState {
  const [state, setState] = useState<ResolveState>({ kind: 'resolving' });

  useEffect(() => {
    let cancelled = false;
    setState({ kind: 'resolving' });
    resolveConnection(params)
      .then((connection) => {
        if (!cancelled) setState({ kind: 'ready', connection });
      })
      .catch((error: unknown) => {
        if (!cancelled) setState({ kind: 'error', error });
      });
    return () => {
      cancelled = true;
    };
    // `params` is a stable reference (parsed via useMemo on the search params).
  }, [params]);

  return state;
}

function StudioConnector({ params }: { params: ParsedStudioParams }) {
  const resolved = useResolvedConnection(params);

  if (resolved.kind === 'resolving') return <ConnectionPending />;
  if (resolved.kind === 'error') return <HandshakeError error={resolved.error} />;
  return <StudioBody connection={resolved.connection} />;
}

function HandshakeError({ error }: { error: unknown }) {
  if (error instanceof StudioAuthError) {
    return (
      <ConnectionError
        title="Studio server rejected this origin"
        message="The CLI server didn't recognize this page's origin, so it wouldn't hand over the session token."
        hint="Make sure the CLI's --allow-origin matches this site, then reopen the studio from the URL it printed."
        showCommand={false}
      />
    );
  }
  if (error instanceof StudioConnectionError) {
    return (
      <ConnectionError
        title="Couldn't reach the studio"
        message={error.message}
        hint="Your `lintscope` CLI may have exited. Restart it and reopen the studio from the URL it prints."
      />
    );
  }
  return (
    <ConnectionError
      title="Couldn't start the studio session"
      message={error instanceof Error ? error.message : String(error)}
      hint="Try reopening the studio from the URL the CLI printed."
      showCommand={false}
    />
  );
}

function StudioBody({ connection }: { connection: StudioConnection }) {
  const { state } = useStudioData(connection);
  const fetchSource = useCallback(
    (relativePath: string) => studioApi.file(connection, relativePath),
    [connection],
  );

  if (state.kind === 'pending') {
    return <ConnectionPending />;
  }

  if (state.kind === 'auth-error') {
    return (
      <ConnectionError
        title="Token rejected by studio server"
        message="The CLI created a single-use token. Was this URL hand-edited, or is an older browser tab still open?"
        hint={`Close this tab and reopen the studio from a fresh \`${connection.host ?? 'localhost'}\` CLI run.`}
      />
    );
  }

  if (state.kind === 'connection-error') {
    return (
      <ConnectionError
        title="Couldn't reach the studio"
        message={state.message}
        hint="Your `lintscope` CLI may have exited. Restart it and reopen the studio from the URL it prints."
      />
    );
  }

  if (state.kind === 'schema-error') {
    return (
      <ConnectionError
        title="Studio server returned an unexpected shape"
        message={`Endpoint ${state.endpoint}: ${state.details}`}
        hint="Your CLI version may be newer or older than this hosted UI. Try `npm i -g lintscope@latest`."
        showCommand={false}
      />
    );
  }

  // state.kind === 'ready'
  return (
    <div className="flex flex-col gap-6">
      <header className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <p className="font-mono text-xs uppercase tracking-widest text-zinc-500">
            {state.init.name} · studio
          </p>
          <h1 className="text-2xl font-semibold tracking-tight">Lint diagnostics</h1>
          <p className="text-xs text-zinc-500 dark:text-zinc-500">
            {state.init.linters.map((l) => `${l.name}@${l.version}`).join(', ')}
            {state.init.capabilities.watch && (
              <span className="ml-2 inline-flex items-center gap-1 rounded bg-emerald-50 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-emerald-700 ring-1 ring-inset ring-emerald-600/20 dark:bg-emerald-950/40 dark:text-emerald-300 dark:ring-emerald-400/30">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
                watching
              </span>
            )}
            {!state.init.capabilities.scan && (
              <span className="ml-2 inline-flex items-center gap-1 rounded bg-zinc-100 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-zinc-600 ring-1 ring-inset ring-zinc-500/20 dark:bg-zinc-900 dark:text-zinc-400 dark:ring-zinc-400/20">
                <span className="h-1.5 w-1.5 rounded-full bg-zinc-400" />
                render-only
              </span>
            )}
          </p>
        </div>
      </header>
      <LintDashboard
        report={state.report}
        {...(state.init.capabilities.file ? { onFetchSource: fetchSource } : {})}
      />
    </div>
  );
}
