// Adapter layer — re-exported from @lintscope/adapters (its canonical home)
// so existing consumers of @lintscope/core keep working unchanged.
export {
  type BiomeDiagnostic,
  type BiomeReport,
  buildEslintArgs,
  type DetectedBiomeConfig,
  type DetectedEslintConfig,
  type DetectedOxcConfig,
  detectBiomeConfig,
  detectEslintConfig,
  detectOxcConfig,
  type EslintLintMessage,
  type EslintLintResult,
  getAdapter,
  type LinterAdapter,
  listAdapters,
  type MapBiomeContext,
  type MapEslintContext,
  type MapOxcContext,
  mapBiomeResults,
  mapEslintResults,
  mapOxcResults,
  type OxcDiagnostic,
  type OxcLabel,
  type OxcReport,
  type PathImpl,
  type ResolvedLinterBin,
  type ResolveLinterBinDeps,
  type ResolveLinterBinOptions,
  type ResolveLinterVersionDeps,
  registerAdapter,
  relativeDisplayPath,
  resolveLinterBin,
  resolveLinterVersion,
  runAdapter,
  toPosix,
} from '@lintscope/adapters';
export { type DetectedLinter, detectLinter, detectLinters } from './detect-config';
export {
  type LinterName,
  mergeReports,
  type ResolvedLinterChoice,
  type ResolvedLintScope,
  type ResolveLintScopeOptions,
  type RunLinterOptions,
  type RunLintersOptions,
  type RunLintersResult,
  resolveLinterChoice,
  resolveLintScope,
  runLinter,
  runLinters,
  type SkippedLinter,
} from './run-linter';
